#ifndef __ELLIPTIC_CURVE_ALGEBRA_STATUS_H__
#define __ELLIPTIC_CURVE_ALGEBRA_STATUS_H__

typedef enum
{
    ELLIPTIC_CURVE_ALGEBRA_SUCCESS               =  0,
    ELLIPTIC_CURVE_ALGEBRA_UNKNOWN_ERROR         = -1,
    ELLIPTIC_CURVE_ALGEBRA_INVALID_PARAMETER     = -2,
    ELLIPTIC_CURVE_ALGEBRA_INVALID_SCALAR        = -3,
    ELLIPTIC_CURVE_ALGEBRA_INVALID_POINT         = -4,
    ELLIPTIC_CURVE_ALGEBRA_INSUFFICIENT_BUFFER   = -5,
    ELLIPTIC_CURVE_ALGEBRA_OUT_OF_MEMORY         = -6,
    ELLIPTIC_CURVE_ALGEBRA_INVALID_SIGNATURE     = -7,
} elliptic_curve_algebra_status;

#endif //#ifndef __ELLIPTIC_CURVE_ALGEBRA_STATUS_H__