
FROM ubuntu:focal

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt install -y \
    build-essential \
    uuid-dev \
    libssl-dev \
    libsecp256k1-dev \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /var/cache/apt/archives/*

WORKDIR /usr/src/mpc-lib