#pragma once

typedef enum cosigner_status_t
{
    COSIGNER_STATUS_SUCCESS,
    COSIGNER_STATUS_INVALID_PARAMETER,
    COSIGNER_STATUS_BAD_PRIVATE_KEY,
    COSIGNER_STATUS_BAD_KEY_LEN,
    COSIGNER_STATUS_BAD_DATA_LEN,
    COSIGNER_STATUS_PUBLIC_KEY_TOO_SMALL,
    COSIGNER_STATUS_SIGNATURE_BLOCK_TOO_SMALL,
    COSIGNER_STATUS_NOT_IMPLEMENTED,
    COSIGNER_STATUS_UNKNOWN_ALGORITHM,
    COSIGNER_STATUS_INTERNAL_ERROR
} cosigner_status;


